adding root partition & filesystem resize code

diff --git a/tinker-config b/tinker-config
--- a/tinker-config
+++ b/tinker-config
@@ -32,7 +32,40 @@ you have heavily customised your installation.\
 }
 
 do_expand_rootfs() {
-	ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
+
+  ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
+  resize2fs /dev/$ROOT_PART
+
+  PART_NUM=${ROOT_PART#mmcblk0p}
+
+
+  SD_SIZE=$(parted /dev/mmcblk0 -ms  p | grep mmcblk0 | cut -f 2 -d:)
+  PART_SIZE=$( parted /dev/mmcblk0 -ms  p | grep ^$PART_NUM | cut -f 3 -d:)
+
+  if [ $SD_SIZE = $PART_SIZE ]; then
+	  whiptail --msgbox "SD size is $SD_SIZE and root partition is $PART_SIZE \n\nNo resize needed !" 20 60 2
+	  return 0
+  fi
+
+# Get the starting offset of the root partition
+  PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
+  [ "$PART_START" ] || return 1
+  # Return value will likely be error for fdisk as it fails to reload the
+  # partition table because the root fs is mounted
+  fdisk /dev/mmcblk0 <<EOF
+p
+d
+$PART_NUM
+n
+p
+$PART_NUM
+$PART_START
+
+w
+EOF
+  ASK_TO_REBOOT=1
+
+ whiptail --msgbox "The root partition has been resized to $SD_SIZE \n\n The filesystem will be resized after a reboot" 20 60 2
 }
 
 do_change_pass() {
